---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Remove password prompt for sudoers
      become: yes
      become_method: sudo
      command:
        cmd: "sudo sed -i '/^%sudo/c\\%sudo ALL=(ALL) NOPASSWD: ALL' /etc/sudoers"
        warn: false
