---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Change the sudoers file
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'sudo /usr/sbin/visudo -cf %s'
