---

- name: Update sshd_config to disable root password login
  hosts: all
  become: true

  tasks:
    - name: Backup original sshd_config
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.bak
      register: backup_result

    - name: Disable root password login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
        backup: yes
      register: update_result

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
