---

- name: Update sshd_config to disable all password login
  hosts: ubuntu_servers
  become: true

  tasks:
    - name: Backup original sshd_config
      become: yes
      become_method: sudo
      command:
        cmd: sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
      register: backup_result

    - name: Disable password authentication
      become: yes
      become_method: sudo
      command:
        cmd: "sudo sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config"
        warn: false
      register: update_result

    - name: Restart SSH service
      become: yes
      become_method: sudo
      command:
        cmd: sudo systemctl restart sshd
