---

- hosts: all
  become: yes

  tasks:
    - name: Update package cache
      command: sudo apt-get update
      changed_when: false

    - name: Install fail2ban
      command: sudo apt-get install -y fail2ban

    - name : Copy configuration
      become: yes
      become_method: sudo
      copy:
        src: configfiles/debian-sshd-default.conf
        dest: /tmp/

    - name: Copy to directory fail2ban
      become: yes
      become_method: sudo
      command: sudo mv /tmp/debian-sshd-default.conf /etc/fail2ban/jail.d/

    - name: restart fail2ban
      become: yes
      become_method: sudo
      command: 
        cmd: sudo systemctl restart fail2ban
