---

- name: Check if Ubuntu servers need reboot
  hosts: all
  gather_facts: true

  tasks:
    - name: Check if reboot is required
      command: /usr/sbin/needrestart -r
      changed_when: false
      register: reboot_status
      failed_when: reboot_status.rc > 2

    - name: Display reboot status
      debug:
        msg: "Reboot required"
      when: reboot_status.stdout.find("Reboot is required") != -1
