---

- name: Query disk space on Ubuntu servers
  hosts: ubuntu_servers
  become: true
  gather_facts: true

  tasks:
    - name: Check disk space
      command: df -h
      register: disk_space_output

    - name: Parse disk space output
      set_fact:
        disk_space_data: "{{ disk_space_output.stdout_lines[1:] | map('regex_replace', '^\\S+\\s+', '') | map('split', None, 1) | list }}"

    - name: Display disk space information
      debug:
        msg: "Mount: {{ item[5] }}, Available: {{ item[3] }}, Used: {{ item[2] }}"
      loop: "{{ disk_space_data }}"
