---

- name: Reboot hosts if required
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Check if reboot is required
      command: sudo /usr/sbin/needrestart -r
      changed_when: false
      register: reboot_status
      failed_when: reboot_status.rc > 2

    - name: Display reboot status
      debug:
        msg: "Reboot required"
      when: reboot_status.stdout.find("Reboot is required") != -1
     
    - name: Reboot hosts
      command: sudo shutdown -r now
      async: 0
      poll: 0
      when: reboot_status.stdout.find("Reboot is required") != -1
    
    #- name: Reboot hosts
    #  become: yes
    #  reboot:
    #    reboot_timeout: 300
    #    pre_reboot_delay: 0
    #    post_reboot_delay: 30
    #    test_command: uptime
    #    connect_timeout: 5
      #  reboot_timeout_action: force
      #when: reboot_status.stdout.find("Reboot is required") != -1
