---

- name: Reboot Ubuntu Servers if Required
  hosts: ubuntu_servers
  gather_facts: yes

  tasks:
    - name: Check if system requires a reboot
      shell: /usr/lib/update-notifier/apt-check --human-readable
      register: reboot_check
      changed_when: false
      ignore_errors: true

    - name: Reboot the server
      reboot:
      when: reboot_check.rc == 0 and 'packages can be updated' in reboot_check.stdout
