---

- name: Reboot hosts if required
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Check if reboot is required
      command: sudo /usr/sbin/needrestart -r
      changed_when: false
      register: reboot_status
      failed_when: reboot_status.rc > 2

    - name: Display reboot status
      debug:
        msg: "Reboot required"
      when: reboot_status.stdout.find("Reboot is required") != -1
     
    - name: Reboot hosts
      command: sudo shutdown -r now
      async: 0
      poll: 0
      when: reboot_status.stdout.find("Reboot is required") != -1
