---
- name: Check for required reboots on Ubuntu servers
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Gather reboot status
      shell: "[ -f /var/run/reboot-required ] && echo 'required' || echo 'not required'"
      register: reboot_status
      changed_when: false

    - name: Display reboot status
      debug:
        msg: "Reboot is {{ reboot_status.stdout }}"
