---

- name: Update starship.toml file on ubuntu servers
  hosts: all
  become: true

  tasks:
    - name: Backup original bashrc config
      become: yes
      become_method: sudo
      command:
        cmd: sudo cp ~/.config/starship.toml ~/.config/starship.toml.bak
      register: backup_result
      when: ansible_distribution == 'Ubuntu'

    - name : Copy starship config file to remote servers
      become: yes
      become_method: sudo
      copy:
        src: configfiles/starship.toml
        dest: /tmp/
      when: ansible_distribution == 'Ubuntu'

    - name: Move config to appropriate location
      become: yes
      become_method: sudo
      command: sudo mv /tmp/starship.toml ~/.config/starship.toml
      when: ansible_distribution == 'Ubuntu'
