---

- name: Update and upgrade Ubuntu servers
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Update package cache
      become: yes
      become_method: sudo
      command:
        cmd: sudo apt update

    - name: Upgrade packages
      become: yes
      become_method: sudo
      command:
        cmd: sudo apt upgrade -y
