---

- name: Update and upgrade Ubuntu servers
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes

